Implement live update mechanism
ad-freiburg/qlever-ui pull request #60
Opened 2023-10-11 13:18 UTC by RobinTF

With the changes introduced in https://github.com/ad-freiburg/qlever/pull/1119 this allows to track computation steps in real-time.

2023-10-12 12:30 UTC, joka921 requested changes
1-1 with Robin, small changes requested.

2023-10-12 12:30 UTC, joka921 commented on backend/static/js/helper.js
> +    } else {
if (condition_switched) {
  return;
}
// no else.

2023-10-12 12:30 UTC, joka921 commented on backend/static/js/qleverUI.js
> +  const queryId = crypto.randomUUID();
Integrate a fallback for local (this includes VPNs) testing that also works without HTTPS.

2023-10-12 12:32 UTC, RobinTF commented on backend/static/js/qleverUI.js
> +      visualise(false);
Also we need to close the socket here if it's not already closed to prevent it from waiting forever

2023-10-19 16:35 UTC, hannahbast requested changes
1-1 with Robin, looks great, we discussed a few minor changes:

1. fetch instead of ajax (unrelated but code touched by this PR)
2. Older ws messages should not overwrite the runtime information for the current query
3. Very minor stuff

2023-10-19 23:15 UTC, hannahbast commented
@RobinTF I fixed the scrolling issue and the tree is now nicer, with the "not started" boxes greyed out. It's active on most QLever instance on https://qlever.cs.uni-freiburg.de already. Unfortunately, QLever is so fast, that you have to search hard for a meaningful query that takes longer. Here is a good one, where one can see it in (not too fast and not too) slow motion: https://qlever.cs.uni-freiburg.de/uniprot/YfnYmn

2023-10-20 17:17 UTC, RobinTF commented
@hannahbast 
>     1. The operation that is currently being computed is also shown as "not started". How hard would it be to show that as "started"?

That would be pretty straightforward. We just need to add a "started" status within qlever, and add a function that is called in `Operation::getResult` over at the qlever repo that sets and broadcasts this event. Then we just need to adjust qlever-ui a bit so it properly displays the new status nicely.

>     2. The operation that is currently being computed sometimes shows a negative time. For example, the last SORT operation for this query: https://qlever.cs.uni-freiburg.de/wikidata/G39jNj (clear the cache before executing it, otherwise it might be too fast)

That seems to be a bug within qlever itself: https://github.com/ad-freiburg/qlever/blob/baa2a4f2fff71e9dc8e700dcd06cb4b5deef2419/src/engine/RuntimeInformation.cpp#L125-L126

This happens when the total time is 0 and the duration of the child durations is subtracted from 0. I don't know enough about query planning to say what's the best fix for this. This occurs at a stage where the total time can't be known yet, so either we fill it with an estimated guess to subtract from, or we have to rethink the values we send within intermediate steps.

2023-10-20 17:21 UTC, RobinTF commented
@hannahbast Also fixing the problem with overwritten runtime information is slightly trickier than I initially thought because of the request history. The simplest "solution" would be to drop the history entirely, assuming it is not really used by anyone (would also clean up the codebase), but if that's not an option I need to keep track of query ids which also requires me to touch the sparql autocomplete feature which also stores its requests in the history. Pretty messy stuff. Thoughts?

2023-11-20 18:57 UTC, hannahbast requested changes
Thanks a lot! Some minor changes left + one bug (maybe in the backend):

When I issue the same query multiple times (for example, by pressing the "Execute" button twice for the same long-running query), the runtime information is **identical** except for the root operation.

2023-11-20 18:57 UTC, hannahbast commented on backend/static/js/qleverUI.js
> +// Map guarantees to keep insertion order
// Note: when we later iterate over this `Map`, we get the key-value pairs in the order in which the keys were first inserted.

2023-11-20 18:57 UTC, hannahbast commented on backend/static/js/qleverUI.js
> +// several qlever-ui instances.
```suggestion
// different instances of the Qlever UI running at the same time.
```

2023-11-20 18:57 UTC, hannahbast commented on backend/static/js/qleverUI.js
> +// Map guarantees to keep insertion order
Better move this comment to line 808 (or so), where we actually iterate over the map.

2023-11-20 18:57 UTC, hannahbast commented on backend/static/js/helper.js
> +      request_log.delete(request_log.keys().next().value);
// Note: `keys().next()` is the key that was inserted first.

2023-11-20 18:57 UTC, hannahbast commented on backend/static/js/helper.js
> +  if (previousTimeStamp < queryUpdate.updateTimeStamp) {
// If newer runtime info for existing query or new query.

2023-11-20 18:57 UTC, hannahbast commented on backend/static/css/style.css
> +  /* max-width: 40em; */
These can be removed now (was still playing with the look, but it seems OK for now).

2023-11-20 22:20 UTC, RobinTF commented
@hannahbast I Implemented the changes and I have a theory for the potential bug we encountered, which I'll discuss with Johannes soon. But this PR here is definitely finished

2023-11-22 08:35 UTC, RobinTF commented
@hannahbast Turns out the "potential bug" is actually a feature and intended behaviour of qlever as @joka921 found out. So everything is fine here

2023-11-23 20:57 UTC, hannahbast approved these changes
This looks great now, thanks a lot!

2023-11-23 21:14 UTC, merged